const router = require("express").Router();
const { anime } = require("../controllers/anime");
const { vdsexy } = require("../controllers/vdsexy");
const { jocker } = require("../controllers/jocker");
const { horimiyamura } = require("../controllers/horimiyamura");
const { narutohinata } = require("../controllers/narutohinata");
const { houtarouchitanda } = require("../controllers/houtarouchitanda");
const { shikizum } = require("../controllers/shikizum");
const { avtdoi } = require("../controllers/avtdoi");
const { sakutamai } = require("../controllers/sakutamai");
const { nobitashizuka } = require("../controllers/nobitashizuka");
const { shinichiran } = require("../controllers/shinichiran");
const { gaiditbu } = require("../controllers/gaiditbu");
const { gaivuto } = require("../controllers/gaivuto");
const { gaisexy } = require("../controllers/gaisexy");
const { avt } = require("../controllers/avt");
const { animevd } = require("../controllers/animevd");
const { mp3 } = require("../controllers/mp3");
const { apigif } = require("../controllers/apigif");
const { aodai } = require("../controllers/aodai");
const { vdchill } = require("../controllers/vdchill");
const { vdnhacchu } = require("../controllers/vdnhacchu");
const { vdnaruto } = require("../controllers/vdnaruto");
const { vdlufy } = require("../controllers/vdlufy");
const { vdmusic } = require("../controllers/vdmusic");
const { vdtet } = require("../controllers/vdtet");
const { nino } = require("../controllers/nino");
const { thinh } = require("../controllers/thinh");
const { canh } = require("../controllers/canh");
const { vdgai } = require("../controllers/vdgai");
const { onepice } = require("../controllers/onepice");
const { goku } = require("../controllers/goku");
const { loli } = require("../controllers/loli");
const { mirai } = require("../controllers/mirai");
const { mui } = require("../controllers/mui");
const { domixi } = require("../controllers/domixi");
const { meme } = require("../controllers/meme");
const { vdsex } = require("../controllers/vdsex");
const { gura } = require("../controllers/gura");
const { trai } = require("../controllers/trai");
const { vdbautroi } = require("../controllers/vdbautroi");
const { slot } = require("../controllers/slot");
const { sex } = require("../controllers/sex");
const { taixiu } = require("../controllers/taixiu");
const { rem } = require("../controllers/rem");
const { lucky } = require("../controllers/lucky");
const { couple } = require("../controllers/couple");
const { cadao } = require("../controllers/cadao");
const { dovui } = require("../controllers/dovui");
const {vuatiengviet } = require("../controllers/vuatiengviet");
const { ig } = require("../controllers/ig");
const { tw } = require("../controllers/tw");
const { dhbcv2 } = require("../controllers/dhbcv2");
const { dhbcv1 } = require("../controllers/dhbcv1");
const { girl } = require("../controllers/girl");
const { gainhat } = require("../controllers/gainhat");
const { hana } = require("../controllers/hana");
const { vddoraemon } = require("../controllers/vddoraemon");
const { conan } = require("../controllers/conan");
const { robot } = require("../controllers/robot");
const { congchua } = require("../controllers/congchua");
const { itachi } = require("../controllers/itachi");
const { itsuki } = require("../controllers/itsuki");
const { taktopdestiny } = require("../controllers/taktopdestiny");
const { kana } = require("../controllers/kana");
const { sontung } = require("../controllers/sontung");
const { mocchonshikimori } = require("../controllers/mocchonshikimori");
const { jack } = require("../controllers/jack");
const { ghensin } = require("../controllers/ghensin");
const { gainga } = require("../controllers/gainga");
const { gaiviet } = require("../controllers/gaiviet");
const { imgdoraemon } = require("../controllers/imgdoraemon");
const { imgbautroi } = require("../controllers/imgbautroi");
const { du } = require("../controllers/du");
const { lol } = require("../controllers/lol");
const { cu } = require("../controllers/cu");
const { anya } = require("../controllers/anya");
const { ausand } = require("../controllers/ausand");
const { lufy } = require("../controllers/lufy");
const { chitanda } = require("../controllers/chitanda");
const { kurumi } = require("../controllers/kurumi");
const { mong } = require("../controllers/mong");
const { naruto } = require("../controllers/naruto");
const { nude } = require("../controllers/nude");
const { yuulzumi } = require("../controllers/yuulzumi");
const { cosplay } = require("../controllers/cosplay");
const { hocsinh } = require("../controllers/hocsinh");
const { vdtrai } = require("../controllers/vdtrai");
const { vdtamtrang } = require("../controllers/vdtamtrang");
const { giangsinh } = require("../controllers/giangsinh");
const { pinterest } = require("../controllers/pinterest");
const { upload } = require("../controllers/upload");
const { view } = require("../controllers/view");
const { upload1 } = require("../controllers/upload1");
const { vdcos } = require("../controllers/vdcos");
const { vdloli } = require("../controllers/vdloli");
const { home } = 
  //res.sendFile(__dirname + '/routes2.html')
 require("../controllers/home");

router.post("/upload", upload);
router.get("/view/upload", view);
router.get("/upload1", upload1);
router.get("/videos/vdanime", animevd);
router.get("/avtdois/sakutamai",sakutamai);
router.get("/avtdois/nobitashizuka",nobitashizuka);
router.get("/avtdois/shinichiran",shinichiran);
router.get("/avtdois/avtdoi",avtdoi);
router.get("/avtdois/shikizum",shikizum);
router.get("/avtdois/houtarouchitanda",houtarouchitanda);
router.get("/avtdois/narutohinata",narutohinata);
router.get("/avtdois/horimiyamura",horimiyamura);
router.get("/images/aodai", aodai);
router.get("/images/meme", meme);
router.get("/images/gaivuto", gaivuto);
router.get("/images/gaiditbu", gaiditbu);
router.get("/images/gaisexy", gaisexy);
router.get("/images/avt", avt);
router.get("/images/loli", loli);
router.get("/images/domixi", domixi);
router.get("/images/onepice", onepice);
router.get("/images/canh", canh);
router.get("/images/trai", trai);
router.get("/images/6mui", mui);
router.get("/images/gura", gura);
router.get("/images/mirai", mirai);
router.get("/images/goku", goku);
router.get("/images/robot", robot);
router.get("/images/congchua", congchua);
router.get("/images/nude", nude);
router.get("/images/naruto", naruto);
router.get("/images/itachi", itachi);
router.get("/images/lol", lol);
router.get("/images/mong", mong);
router.get("/images/du", du);
router.get("/images/cu", cu);
router.get("/images/yuulzumi", yuulzumi);
router.get("/images/imgbautroi", imgbautroi);
router.get("/images/imgdoraemon", imgdoraemon);
router.get("/images/conan", conan);
router.get("/images/kurumi", kurumi);
router.get("/images/chitanda", chitanda);
router.get("/images/gaiviet", gaiviet);
router.get("/images/gainga", gainga);
router.get("/images/ghensin", ghensin);
router.get("/images/anya", anya);
router.get("/images/sontung", sontung);
router.get("/images/jack", jack);
router.get("/images/mocchonshikimori", mocchonshikimori);
router.get("/images/ausand", ausand);
router.get("/images/itsuki", itsuki);
router.get("/images/kana", kana);
router.get("/images/lufy", lufy);
router.get("/images/cosplay", cosplay);
router.get("/images/hocsinh", hocsinh);
router.get("/images/trai", trai);
router.get("/game/slot", slot);
router.get("/images/gif", apigif);
router.get("/images/tw", tw);
router.get("/images/ig", ig);
router.get("/images/girl", girl)
router.get("/images/gainhat", gainhat);
router.get("/images/hana", hana);
router.get("/images/anime", anime);
router.get("/images/rem", rem);
router.get("/images/taktopdestiny", taktopdestiny);
router.get("/images/lucky", lucky);
router.get("/images/nino", nino);
router.get("/images/couple", couple);
router.get("/images/sex", sex);
router.get("/videos/vddoraemon", vddoraemon);
router.get("/videos/vdtrai", vdtrai);
router.get("/videos/vdtamtrang", vdtamtrang);
router.get("/video//vdbautroi", vdbautroi);
router.get("/videos/vdchill", vdchill);
router.get("/videos/vdnaruto", vdnaruto);
router.get("/videos/vdlufy", vdlufy);
router.get("/videos/vdnhacchu", vdnhacchu);
router.get("/videos/vdgai", vdgai);
router.get("/videos/music", vdmusic);
router.get("/videos/vdtet", vdtet);
router.get("/videos/vdsex", vdsex);
router.get("/videos/vdsexy", vdsexy);
router.get("/videos/vdcosplay", vdcos);
router.get("/videos/vdloli", vdloli);
router.get("/mp3", mp3);
router.get("/game/tx", taixiu);
router.get("/text/cadao", cadao);
router.get("/text/jocker", jocker);
router.get("/game/dovui", dovui);
router.get("/game/vuatiengviet", vuatiengviet);
router.get("/game/dhbcv1", dhbcv1);
router.get("/game/dhbcv2", dhbcv2);
router.get("/text/thinh", thinh);
router.get("/canvas/giangsinh", giangsinh);
router.get("/search/pinterest",pinterest);

router.get('/', (req, res) => {
  res.sendFile(__dirname + 'index.html')
})

module.exports = router; 